# Generated by Django 5.0.6 on 2024-07-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0002_problems_creater"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problems",
            name="creater",
        ),
    ]
